title: Prerequisite Knowledge for Civil Engineering Master
author: TU Delft, Faculty of Civil Engineering and Geosciences, project team PRE-for-CEM
logo: images/logo.png

execute:
  execute_notebooks: auto

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/TUDelft-CITG/pre-for-cem
  path_to_book: book
  branch: publish

# GitHub Issues button and repository link
html:
  use_repository_button: true
  use_issues_button: true
